env: "local"

server:
  host: "localhost"
  port: "3000"

postgres:
  user: "postgres"
  password: "password"
  host: "postgres"
  port: "5432"
  name: "postgres"
  ssl_mode: false

redis:
  name: 0
  host: "localhost"
  port: "6379"
  user : ""
  password: ""

nats:
  url: "nats:4222"

clickhouse:
  addr: "clickhouse:19000"
  database: "default"
  username: "default"
  password: ""

