env: "local"

server:
  host: "localhost"
  port: "3000"

postgres:
  user: "postgres"
  password: ""
  host: "localhost"
  port: "5432"
  name: "postgres"
  ssl_mode: false

redis:
  name: 0
  host: "localhost"
  port: "6379"
  user : ""
  password: ""
