env: "local"

server:
  port: ":3000"

postgres:
  user: "postgres"
  password: "password"
  host: "postgres"
  port: "5432"
  name: "postgres"
  ssl_mode: "disable"

redis:
  name: 0
  host: "redis"
  port: "6379"
  user : ""
  password: ""

nats:
  url: "nats:4222"

clickhouse:
  addr: "clickhouse:9000"
  database: "default"
  username: "default"
  password: ""

